export const state = {
  companies: [],
  hierarchies: [],
  senders: [],
  templates: [],
  campaigns: [],
  activeCampaign: null,
  selectedCampaignId: null,
  searchQuery: '',
  selectedCompany: 'ALL',
  selectedCrmStatus: 'ALL',
  selectedCoverageStatus: 'ALL',
  selectedPriorityFilter: 'ALL',
  contactsPage: 1,
};
